# Generated by Django 4.2 on 2025-02-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirebaseStorage', '0003_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
