# Generated by Django 4.2 on 2024-11-23 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_remove_post_image_delete_image_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='share_body',
        ),
    ]
