# Generated by Django 4.2 on 2025-02-09 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_comment_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
